#!/bin/bash
cd ../
cd slimkat4.4
. build/envsetup.sh
echo ""
echo ""
echo "########################"
echo "Type code name of device"
echo "########################"
echo ""
choice=""
read choice
brunch "$choice"
