#!/bin/bash
cd
path=""
echo "enter path to your source"
read path
cd $Path
. build/envsetup.sh
echo ""
echo "########################"
echo "Type code name of device"
echo "########################"
echo ""
choice=""
read choice
mka bacon -j10 $choice
