#!/bin/bash
cd ../
cd slimkat4.4
. build/envsetup.sh
echo "Enter commit message"
choice=""
echo ""
echo ""
echo "########################"
echo "Type code name of device"
echo "########################"
echo ""
echo ""
read choice
brunch "$choice"
