#!/bin/bash
adb devices
echo ""
echo "#########################################################"
echo ""
echo "Enter path to your Boot or recovery whatever you are flashing "
echo ""
echo "#########################################################"
echo ""
echo "For example mine boot.img path is :- mmcblk0p5"
echo "And recovery path is:- mmcblk06"
echo "#########################################################"
flash=""
read flash
adb shell mount -o rw,remount /system
echo ""
echo "#########################################################"
echo "Path to your boot.img or recovery.img"
echo "#########################################################"
echo ""
recovery=""
read recovery
adb push $recovery /system/bin/$recovery
echo "#/bin/bash
cd /system/bin
dd if=$recovery of=/dev/block/$flash" > tmp
chmod 775 tmp
adb push tmp /system/bin/tmp
adb shell tmp
adb shell rm /system/bin/$recovery
adb shell rm /system/bin/tmp
adb reboot
rm tmp


