#!/bin/bash
adb devices
echo "press enter  when device booted into recovery"
adb reboot recovery
enter=""
read enter
echo ""
echo "#########################################################"
echo ""
echo "Enter path to your Boot or recovery whatever you are flashing "
echo ""
echo "#########################################################"
echo ""
echo "For example mine boot.img path is :- mmcblk0p5"
echo "And recovery path is:- mmcblk06"
echo "#########################################################"
flash=""
read flash
echo ""
echo "#########################################################"
echo "Path to your boot.img or recovery.img"
echo "#########################################################"
echo ""
recovery=""
read recovery
adb push $recovery /system/bin/boot.img
echo "#/bin/bash
cd /system/bin
dd if=boot.img of=/dev/block/$flash" > tmp
chmod 775 tmp
adb push tmp /system/bin/tmp
adb shell tmp
adb shell rm /system/bin/boot.img
adb shell rm /system/bin/tmp
adb reboot system
rm tmp


