#!/bin/bash
git init 
git add .
git status
echo "Enter commit message"
commit=""
read commit
git commit -m "$commit"
echo "Enter Url"
url=""
read url
git remote add origin "$url"
branch=""
echo "Enter branch name"
read branch
git branch -m $branch
git push origin $branch
echo "#!/bin/bash
git add .
git push origin $branch" > git
chmod 775 git
echo "An scrpit has been genrated next time type  git commit -m \"your message\" && \"./git\" to publish   "
me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
rm $me

sleep 5
