#!/bin/bash
echo "########################"
echo "Enter device code name "
echo "########################"
code=""
read code
touch $code.xml
echo ""
echo "########################"
echo "Enter device repo address"
echo "For example :- Grace5921/android_device_kyleve"
echo "########################"
echo ""
devicerepo=""
read devicerepo
echo ""
echo "########################"
echo "Enter branch name which you want to dowload for $code"
echo "########################"
echo ""
devicebranch=""
read devicebranch
echo "########################"
echo "From where you want to sync this device tree "
echo "For example :- Github , bitbucket ,etc"
echo "########################"
echo ""
devicegit=""
read devicegit
echo "########################"
echo "Enter device tree path "
echo "For example :- device/samsung/kyleve"
echo "########################"
echo ""
devicepath=""
read devicepath 
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" >> $code.xml
echo "<manifest>" >> $code.xml
echo "<!-- This is device tree related stuff -->" >> $code.xml
echo "<project path=\"$devicepath\" name=\"$devicerepo\" revision=\"$devicebranch\" remote=\"$devicegit\" />" >> $code.xml
########################################################################################################################
echo "########################"
echo "Enter vendor repo address"
echo "For example :- Grace5921/android_vendor_kyleve"
echo "########################"
echo ""
vendorrepo=""
read vendorrepo
echo ""
echo "########################"
echo "Enter branch name which you want to dowload for $code"
echo "########################"
echo ""
vendorbranch=""
read vendorbranch
echo "########################"
echo "Enter device tree path "
echo "For example :- vendor/samsung/kyleve"
echo "########################"
echo ""
vendorpath=""
read vendorpath
echo "########################"
echo "From where you want to sync this device tree "
echo "For example :- Github , bitbucket ,etc"
echo "########################"
echo ""
venodrgit=""
read venodrgit
echo "<!-- This is vendor tree related stuff -->" >> $code.xml
echo "<project path=\"$vendorpath\" name=\"$vendorrepo\" revision=\"$vendorbranch\" remote=\"$venodrgit\" />" >> $code.xml
########################################################################################################################
echo "########################"
echo "Enter kernel repo address"
echo "For example :- Grace5921/android_kernel_kyleve"
echo "########################"
echo ""
kernelrepo=""
read kernelrepo
echo ""
echo "########################"
echo "Enter branch name which you want to dowload for $code"
echo "########################"
echo ""
kernelbranch=""
read kernelbranch
echo "########################"
echo "Enter device tree path "
echo "For example :- kernel/samsung/kyleve"
echo "########################"
echo ""
kernelpath=""
read kernelpath
echo "########################"
echo "From where you want to sync this device tree "
echo "For example :- Github , bitbucket ,etc"
echo "########################"
echo ""
kernelgit=""
read kernelgit
echo "<!-- This is kernel tree related stuff -->" >> $code.xml
echo "<project path=\"$kernelpath\" name=\"$kernelrepo\" revision=\"$kernelbranch\" remote=\"$kernelgit\" />" >> $code.xml
echo "</manifest>" >> $code.xml
mkdir local_manifests
mv $code.xml local_manifests/$code.xml
echo ""
echo "roomservices.xml is ready for $code "
echo "Copy local_manifests folder to .repo and repo sync "
