#!/bin/bash
#Permission
chmod 775 tools/sdat2img.py
chmod 775 tools/rimg2sdat
chmod 775 tools/make_ext4fs
chmod 775 tools/xterm
#Dir
mkdir rom 
mkdir rom/output
cd rom 
#Copy
cp ../tools/sdat2img.py sdat2img.py
cp ../tools/rimg2sdat rimg2sdat
cp ../tools/make_ext4fs make_ext4fs
cp ../tools/xterm xterm
#Output
echo "#######################"
echo "Enter path to your rom.zip "
echo "#######################"
#Path to zip
path=""
read path
cp $path tmp.zip
unzip tmp.zip
#Extract system
./sdat2img.py system.transfer.list system.new.dat system.img
rm system.new.dat
#Mount
sudo mount -t ext4 -o loop system.img output/
echo "##############################################"
echo "Press ctrl+c in terminal when changes are done "
echo "##############################################"
#Changes
xterm -e ./xterm
#make image
echo "Enter Image size in bytes"
size=""
read size
sudo ./make_ext4fs -T 0 -S file_contexts -l $size -a system system_new.img output/
./rimg2sdat system_new.img
sudo umount system.img output/
name=""
echo "################"
echo "Enter zip name "
echo "###############"
read name
zip $name.zip -r install/ system.new.dat system.patch.dat system.transfer.list boot.img file_contexts META-INF/ install/ system/
mv $name.zip ../$name.zip
cd ../
rm -rf rom

